[2021-11-10 23:19:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:19:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":28,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":0}},"time":1636557596}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:20:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:20:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":28,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":0}},"time":1636557601}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:20:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:20:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":28,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":0}},"time":1636557606}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:20:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:20:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":33,"packet_sent":28,"packet_lost":0,"message_received":0,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":0}},"time":1636557611}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:21:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:21:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557711}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:21:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:21:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557716}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557721}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557726}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557731}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":39,"packet_sent":32,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557736}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557741}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557746}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557751}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557756}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557761}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":40,"packet_sent":33,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557766}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":41,"packet_sent":34,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557771}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:22:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:22:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":41,"packet_sent":34,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557646}},"time":1636557776}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":42,"packet_sent":34,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557796}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557801}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557806}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557811}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557816}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557821}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":44,"packet_sent":36,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557826}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557831}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:23:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:23:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557836}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557841}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557846}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557851}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":45,"packet_sent":37,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557856}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557861}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557866}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557871}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557876}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557881}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":46,"packet_sent":38,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557886}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557891}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:24:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:24:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557896}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557901}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557906}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557911}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":47,"packet_sent":39,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557916}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557921}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557926}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557936}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557941}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":48,"packet_sent":40,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557946}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":41,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557951}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:25:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:25:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":49,"packet_sent":41,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557792}},"time":1636557956}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:02] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:image,file=c90fa78f64ee595ef8223d529702e1c1.image,url=https://gchat.qpic.cn/gchatpic_new/2414833004/754044548-3109334902-C90FA78F64EE595EF8223D529702E1C1/0?term=3,subType=1]","message_id":1138689799,"message_seq":85755,"message_type":"group","post_type":"message","raw_message":"[CQ:image,file=c90fa78f64ee595ef8223d529702e1c1.image,subType=1]","self_id":2412125282,"sender":{"age":0,"area":"","card":"                                       ","level":"","nickname":"侑子","role":"member","sex":"unknown","title":"","user_id":2414833004},"sub_type":"normal","time":1636557960,"user_id":2414833004}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":41,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557961}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":41,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557966}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":41,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557971}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":50,"packet_sent":41,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557976}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557981}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557986}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557991}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636557996}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636558001}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":51,"packet_sent":42,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636558006}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":53,"packet_sent":44,"packet_lost":0,"message_received":4,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636557960}},"time":1636558011}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:58] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"[CQ:reply,id=-1612059741][CQ:at,qq=2237553939] [CQ:at,qq=2237553939] 男酮","message_id":923816035,"message_seq":1324349,"message_type":"group","post_type":"message","raw_message":"[CQ:reply,id=-1612059741][CQ:at,qq=2237553939] [CQ:at,qq=2237553939] 男酮","self_id":2412125282,"sender":{"age":0,"area":"","card":"真正的阿巴","level":"","nickname":"Zero Six","role":"member","sex":"unknown","title":"六布阿巴人","user_id":2632795801},"sub_type":"normal","time":1636558016,"user_id":2632795801}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:26:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:26:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":44,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558016}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":44,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558021}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":44,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558026}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":44,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558031}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":54,"packet_sent":44,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558036}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558041}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558046}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558051}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558056}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558061}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":45,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558066}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558071}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:27:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:27:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558076}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558081}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558086}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558091}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":56,"packet_sent":46,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558096}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558101}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558106}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558111}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558116}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558121}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":57,"packet_sent":47,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558126}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558131}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:28:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:28:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558136}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558141}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558146}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558151}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":58,"packet_sent":48,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558156}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":59,"packet_sent":49,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558161}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":59,"packet_sent":49,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558166}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":59,"packet_sent":49,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558171}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":59,"packet_sent":49,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558176}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:29:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:29:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":59,"packet_sent":49,"packet_lost":0,"message_received":5,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558015}},"time":1636558181}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:32:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:32:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":70,"packet_sent":56,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558361}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:32:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:32:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":70,"packet_sent":56,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558366}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:32:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:32:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":71,"packet_sent":57,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558371}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:32:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:32:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":71,"packet_sent":57,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558376}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:33:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:33:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":71,"packet_sent":57,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558381}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:33:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:33:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":71,"packet_sent":57,"packet_lost":0,"message_received":9,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558357}},"time":1636558386}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":63,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558526}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":63,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558531}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":63,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558536}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":63,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558541}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":63,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558546}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:53] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":84,"packet_sent":64,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558551}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:35:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:35:58] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":84,"packet_sent":64,"packet_lost":0,"message_received":15,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558526}},"time":1636558556}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:01] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:01] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:at,qq=1942422015] 真便宜","message_id":1872728285,"message_seq":85761,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=1942422015] 真便宜","self_id":2412125282,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Ancestor","role":"member","sex":"unknown","title":"","user_id":1509102552},"sub_type":"normal","time":1636558559,"user_id":1509102552}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:03] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:03] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":85,"packet_sent":64,"packet_lost":0,"message_received":16,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558559}},"time":1636558561}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:08] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:08] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":85,"packet_sent":64,"packet_lost":0,"message_received":16,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558559}},"time":1636558566}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:13] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:13] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":85,"packet_sent":64,"packet_lost":0,"message_received":16,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558559}},"time":1636558571}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:14] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:14] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"脚踢咖蓝","message_id":-157892249,"message_seq":85762,"message_type":"group","post_type":"message","raw_message":"脚踢咖蓝","self_id":2412125282,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Ancestor","role":"member","sex":"unknown","title":"","user_id":1509102552},"sub_type":"normal","time":1636558572,"user_id":1509102552}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:17] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:image,file=64fe90188b263f8ec5563c2d946f672e.image,url=https://gchat.qpic.cn/gchatpic_new/1509102552/754044548-3044247070-64FE90188B263F8EC5563C2D946F672E/0?term=3,subType=1]","message_id":-2121141775,"message_seq":85763,"message_type":"group","post_type":"message","raw_message":"[CQ:image,file=64fe90188b263f8ec5563c2d946f672e.image,subType=1]","self_id":2412125282,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Ancestor","role":"member","sex":"unknown","title":"","user_id":1509102552},"sub_type":"normal","time":1636558575,"user_id":1509102552}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:18] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:18] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":87,"packet_sent":64,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558576}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:23] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:23] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558581}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:28] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:28] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558586}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:33] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558591}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:38] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:38] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558596}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:43] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:43] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558601}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-10 23:36:48] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-10 23:36:48] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2412125282,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":88,"packet_sent":65,"packet_lost":0,"message_received":18,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636558575}},"time":1636558606}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
