[2021-11-15 16:48:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":67,"packet_sent":60,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966099}},"time":1636966105}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":67,"packet_sent":60,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966099}},"time":1636966110}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":67,"packet_sent":60,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966099}},"time":1636966115}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":67,"packet_sent":60,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966099}},"time":1636966120}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":68,"packet_sent":61,"packet_lost":0,"message_received":2,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966099}},"time":1636966125}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:47] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"又要打材料还得要英雄还要设计图还要幸存者","message_id":1837703582,"message_seq":1333557,"message_type":"group","post_type":"message","raw_message":"又要打材料还得要英雄还要设计图还要幸存者","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966125,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":61,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966130}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:48:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:48:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":61,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966135}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":61,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966140}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":61,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966145}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":69,"packet_sent":61,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966150}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":72,"packet_sent":62,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966155}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":73,"packet_sent":63,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966160}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":74,"packet_sent":63,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966165}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":75,"packet_sent":64,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966170}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":75,"packet_sent":64,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966175}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":77,"packet_sent":64,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966180}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":79,"packet_sent":66,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966185}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:51] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:51] [WARNING]: 上报Event数据 {"client":{"app_id":537097074,"device_kind":"Android","device_name":"Android"},"notice_type":"client_status","online":false,"post_type":"notice","self_id":501273515,"time":1636966189}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":82,"packet_sent":66,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966190}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":83,"packet_sent":67,"packet_lost":0,"message_received":3,"message_sent":1,"disconnect_times":1,"lost_times":0,"last_message_time":1636966125}},"time":1636966195}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:58] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"pve","message_id":-46777329,"message_seq":1333558,"message_type":"group","post_type":"message","raw_message":"pve","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"池水河风","role":"member","sex":"unknown","title":"","user_id":1628139954},"sub_type":"normal","time":1636966195,"user_id":1628139954}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:58] [WARNING]: 上报Event数据 {"duration":60,"group_id":913941037,"notice_type":"group_ban","operator_id":2412125282,"post_type":"notice","self_id":501273515,"sub_type":"ban","time":1636966196,"user_id":1628139954}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:49:59] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:49:59] [WARNING]: 上报Event数据 {"font":0,"message":"/echo 你好，世界","message_id":1748841603,"message_type":"private","post_type":"message","raw_message":"/echo 你好，世界","self_id":501273515,"sender":{"age":0,"nickname":"Oswald Kan","sex":"unknown","user_id":1942422015},"sub_type":"friend","target_id":501273515,"time":1636966197,"user_id":1942422015}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":89,"packet_sent":71,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966200}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":90,"packet_sent":72,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966205}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":90,"packet_sent":72,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966210}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966215}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966220}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966225}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966230}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966235}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":91,"packet_sent":73,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966240}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966245}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966250}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:50:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:50:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966255}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966260}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966265}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":92,"packet_sent":74,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966270}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966275}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966280}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966285}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966290}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966295}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":93,"packet_sent":75,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966300}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966305}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966310}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:51:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:51:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966315}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966320}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966325}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":95,"packet_sent":77,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966330}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966335}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966340}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966345}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966350}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966355}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":96,"packet_sent":78,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966360}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966365}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966370}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:52:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:52:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966375}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966380}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966385}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":97,"packet_sent":79,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966390}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966395}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966400}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966405}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966410}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966415}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":98,"packet_sent":80,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966420}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966425}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966430}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:53:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:53:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966435}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966440}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966445}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":99,"packet_sent":81,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966450}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966455}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966460}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966465}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966470}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966475}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":100,"packet_sent":82,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966480}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966485}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966490}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:54:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:54:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966495}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966500}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966505}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":101,"packet_sent":83,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966510}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966515}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966520}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966525}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966530}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966535}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":103,"packet_sent":85,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966540}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966545}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966550}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:55:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:55:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966555}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966560}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966565}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":104,"packet_sent":86,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966570}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":105,"packet_sent":87,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966575}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":105,"packet_sent":87,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966580}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":105,"packet_sent":87,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966585}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":105,"packet_sent":87,"packet_lost":0,"message_received":5,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966197}},"time":1636966590}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:33] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:33] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"@机器人 浙江疫情","message_id":-1659406366,"message_seq":87709,"message_type":"group","post_type":"message","raw_message":"@机器人 浙江疫情","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Rick Sanchez","role":"member","sex":"unknown","title":"","user_id":2677991554},"sub_type":"normal","time":1636966591,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:35] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:35] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"出个号","message_id":-1976496999,"message_seq":1333559,"message_type":"group","post_type":"message","raw_message":"出个号","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"伏井k🅥","role":"member","sex":"unknown","title":"","user_id":2849699931},"sub_type":"normal","time":1636966593,"user_id":2849699931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":107,"packet_sent":87,"packet_lost":0,"message_received":7,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966593}},"time":1636966595}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:41] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:41] [WARNING]: 上报Event数据 {"group_id":754044548,"message_id":-1659406366,"notice_type":"group_recall","operator_id":2677991554,"post_type":"notice","self_id":501273515,"time":1636966591,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":108,"packet_sent":88,"packet_lost":0,"message_received":7,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966593}},"time":1636966600}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":109,"packet_sent":89,"packet_lost":0,"message_received":7,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966593}},"time":1636966605}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:50] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:50] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:at,qq=2412125282]  浙江疫情","message_id":-36635129,"message_seq":87710,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=2412125282]  浙江疫情","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Rick Sanchez","role":"member","sex":"unknown","title":"","user_id":2677991554},"sub_type":"normal","time":1636966608,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":111,"packet_sent":90,"packet_lost":0,"message_received":8,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966608}},"time":1636966610}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:53] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:53] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"有老pve的那种","message_id":-658446338,"message_seq":1333560,"message_type":"group","post_type":"message","raw_message":"有老pve的那种","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"伏井k🅥","role":"member","sex":"unknown","title":"","user_id":2849699931},"sub_type":"normal","time":1636966611,"user_id":2849699931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:56:57] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"你要说了5块我收了","message_id":-1345857688,"message_seq":1333561,"message_type":"group","post_type":"message","raw_message":"你要说了5块我收了","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966615,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:56:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":113,"packet_sent":90,"packet_lost":0,"message_received":10,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966615}},"time":1636966615}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":113,"packet_sent":90,"packet_lost":0,"message_received":10,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966615}},"time":1636966620}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:05] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"浙江疫情","message_id":-1965568367,"message_seq":87711,"message_type":"group","post_type":"message","raw_message":"浙江疫情","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Rick Sanchez","role":"member","sex":"unknown","title":"","user_id":2677991554},"sub_type":"normal","time":1636966623,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":114,"packet_sent":90,"packet_lost":0,"message_received":11,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966623}},"time":1636966625}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:07] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"\u0026#91;无语\u0026#93;","message_id":333356843,"message_seq":87712,"message_type":"group","post_type":"message","raw_message":"\u0026#91;无语\u0026#93;","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Rick Sanchez","role":"member","sex":"unknown","title":"","user_id":2677991554},"sub_type":"normal","time":1636966625,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:10] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:10] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:at,qq=2677991554] \n查询地区:浙江\r\n目前确诊:1499\n死亡人数:1\n治愈人数:1465\r\n新增确诊:0\r\n现存确诊:33\r\n现存无症状:186\r\n最后更新时间:11月15日16时30分","message_id":1691987901,"message_seq":87713,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=2677991554] \n查询地区:浙江\r\n目前确诊:1499\n死亡人数:1\n治愈人数:1465\r\n新增确诊:0\r\n现存确诊:33\r\n现存无症状:186\r\n最后更新时间:11月15日16时30分","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"真正的机器人","role":"admin","sex":"unknown","title":"","user_id":2412125282},"sub_type":"normal","time":1636966628,"user_id":2412125282}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":116,"packet_sent":90,"packet_lost":0,"message_received":13,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966628}},"time":1636966630}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":117,"packet_sent":91,"packet_lost":0,"message_received":13,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966628}},"time":1636966635}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:20] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"有老pve我加5快","message_id":919504594,"message_seq":1333562,"message_type":"group","post_type":"message","raw_message":"有老pve我加5快","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966637,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":118,"packet_sent":91,"packet_lost":0,"message_received":14,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966637}},"time":1636966640}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":118,"packet_sent":91,"packet_lost":0,"message_received":14,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966637}},"time":1636966645}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:30] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:30] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"10块咱们走咸鱼","message_id":1103738436,"message_seq":1333563,"message_type":"group","post_type":"message","raw_message":"10块咱们走咸鱼","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966648,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:32] [WARNING]: 监听反向WS API时出现错误: websocket: close 1000 (normal) 
[2021-11-15 16:57:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":119,"packet_sent":91,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966650}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:35] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:57:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":119,"packet_sent":91,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966655}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:40] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:57:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":119,"packet_sent":91,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966660}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:45] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:57:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":120,"packet_sent":92,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966665}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:50] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:57:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":120,"packet_sent":92,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966670}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:57:55] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:57:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:57:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":120,"packet_sent":92,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966675}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:00] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":120,"packet_sent":92,"packet_lost":0,"message_received":15,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966648}},"time":1636966680}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:03] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:05] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:05] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:05] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"?","message_id":-542301209,"message_seq":1333564,"message_type":"group","post_type":"message","raw_message":"?","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"伏井k🅥","role":"member","sex":"unknown","title":"","user_id":2849699931},"sub_type":"normal","time":1636966683,"user_id":2849699931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":121,"packet_sent":92,"packet_lost":0,"message_received":16,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966683}},"time":1636966685}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:10] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":121,"packet_sent":92,"packet_lost":0,"message_received":16,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966683}},"time":1636966690}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:15] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":122,"packet_sent":93,"packet_lost":0,"message_received":16,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966683}},"time":1636966695}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:20] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":122,"packet_sent":93,"packet_lost":0,"message_received":16,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966683}},"time":1636966700}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:22] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:24] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:24] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"\u0026#91;嗯嗯\u0026#93;","message_id":-88262114,"message_seq":87714,"message_type":"group","post_type":"message","raw_message":"\u0026#91;嗯嗯\u0026#93;","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"Rick Sanchez","role":"member","sex":"unknown","title":"","user_id":2677991554},"sub_type":"normal","time":1636966702,"user_id":2677991554}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:25] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":123,"packet_sent":93,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966705}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:30] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":123,"packet_sent":93,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966710}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:35] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":123,"packet_sent":93,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966715}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:40] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":123,"packet_sent":93,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966720}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:45] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":125,"packet_sent":95,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966725}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:50] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":125,"packet_sent":95,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966730}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:55] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:56] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:58:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":125,"packet_sent":95,"packet_lost":0,"message_received":17,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966702}},"time":1636966735}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:58:58] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:58:58] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"15块咱们走咸鱼","message_id":-1465248911,"message_seq":1333565,"message_type":"group","post_type":"message","raw_message":"15块咱们走咸鱼","self_id":501273515,"sender":{"age":0,"area":"","card":"真整的阿爸 国际服代肝私","level":"","nickname":"TimGoGuy","role":"member","sex":"unknown","title":"","user_id":641042114},"sub_type":"normal","time":1636966736,"user_id":641042114}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:00] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":126,"packet_sent":95,"packet_lost":0,"message_received":18,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966736}},"time":1636966740}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:05] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":126,"packet_sent":95,"packet_lost":0,"message_received":18,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966736}},"time":1636966745}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:10] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":126,"packet_sent":95,"packet_lost":0,"message_received":18,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966736}},"time":1636966750}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:14] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:15] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:16] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:16] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"16","message_id":832783051,"message_seq":1333566,"message_type":"group","post_type":"message","raw_message":"16","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966754,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":128,"packet_sent":96,"packet_lost":0,"message_received":19,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966754}},"time":1636966755}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:20] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":128,"packet_sent":96,"packet_lost":0,"message_received":19,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966754}},"time":1636966760}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:25] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:27] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":128,"packet_sent":96,"packet_lost":0,"message_received":19,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966754}},"time":1636966765}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:27] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:29] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:29] [WARNING]: 上报Event数据 {"font":0,"message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","message_id":-1001813555,"message_type":"private","post_type":"message","raw_message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","self_id":501273515,"sender":{"age":0,"nickname":"Oswald Kan","sex":"unknown","user_id":1942422015},"sub_type":"friend","target_id":501273515,"time":1636966767,"user_id":1942422015}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:30] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:32] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:32] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":131,"packet_sent":98,"packet_lost":0,"message_received":20,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966767}},"time":1636966770}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:34] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:35] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:36] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:36] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"认真的好吧","message_id":1185182301,"message_seq":1333567,"message_type":"group","post_type":"message","raw_message":"认真的好吧","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"伏井k🅥","role":"member","sex":"unknown","title":"","user_id":2849699931},"sub_type":"normal","time":1636966774,"user_id":2849699931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:37] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:37] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":132,"packet_sent":98,"packet_lost":0,"message_received":21,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966774}},"time":1636966775}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:40] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:42] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:42] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":132,"packet_sent":98,"packet_lost":0,"message_received":21,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966774}},"time":1636966780}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:42] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:44] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:44] [WARNING]: 上报Event数据 {"font":0,"message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","message_id":-1534197720,"message_type":"private","post_type":"message","raw_message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","self_id":501273515,"sender":{"age":0,"nickname":"Oswald Kan","sex":"unknown","user_id":1942422015},"sub_type":"friend","target_id":501273515,"time":1636966782,"user_id":1942422015}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:45] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:45] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:47] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":136,"packet_sent":101,"packet_lost":0,"message_received":22,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966782}},"time":1636966785}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:47] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:47] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"武汉疫情","message_id":-1917187448,"message_seq":87715,"message_type":"group","post_type":"message","raw_message":"武汉疫情","self_id":501273515,"sender":{"age":0,"area":"","card":"TREEING ","level":"","nickname":"Mi manchi","role":"member","sex":"unknown","title":"","user_id":1398017538},"sub_type":"normal","time":1636966785,"user_id":1398017538}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:50] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:52] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:52] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":137,"packet_sent":101,"packet_lost":0,"message_received":23,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966785}},"time":1636966790}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:55] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:57] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:57] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":137,"packet_sent":101,"packet_lost":0,"message_received":23,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966785}},"time":1636966795}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:57] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:57] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:58] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 16:59:59] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:59] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"不想玩堡垒之夜了，打算去打APEX","message_id":-702844980,"message_seq":1333568,"message_type":"group","post_type":"message","raw_message":"不想玩堡垒之夜了，打算去打APEX","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"伏井k🅥","role":"member","sex":"unknown","title":"","user_id":2849699931},"sub_type":"normal","time":1636966797,"user_id":2849699931}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 16:59:59] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 16:59:59] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"\u0026#91;无语\u0026#93;","message_id":347298610,"message_seq":87716,"message_type":"group","post_type":"message","raw_message":"\u0026#91;无语\u0026#93;","self_id":501273515,"sender":{"age":0,"area":"","card":"TREEING ","level":"","nickname":"Mi manchi","role":"member","sex":"unknown","title":"","user_id":1398017538},"sub_type":"normal","time":1636966797,"user_id":1398017538}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:00] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:00] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:00] [WARNING]: 上报Event数据 {"font":0,"message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","message_id":-745983810,"message_type":"private","post_type":"message","raw_message":"/say \u0026#91;CQ:share,url=http://baidu.com,title=百度\u0026#93;","self_id":501273515,"sender":{"age":0,"nickname":"Oswald Kan","sex":"unknown","user_id":1942422015},"sub_type":"friend","target_id":501273515,"time":1636966798,"user_id":1942422015}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:02] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:02] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":141,"packet_sent":102,"packet_lost":0,"message_received":26,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966798}},"time":1636966800}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:04] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:04] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:05] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:06] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:06] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"咱这群里都是老壳子","message_id":-1591976102,"message_seq":1333569,"message_type":"group","post_type":"message","raw_message":"咱这群里都是老壳子","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966804,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:06] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:06] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:at,qq=1398017538] \n查询地区:武汉\r\n目前确诊:50462\n死亡人数:3869\n治愈人数:46587\r\n新增确诊:0\r\n现存确诊:6\r\n现存无症状:17\r\n最后更新时间:11月15日16时30分","message_id":1672768420,"message_seq":87717,"message_type":"group","post_type":"message","raw_message":"[CQ:at,qq=1398017538] \n查询地区:武汉\r\n目前确诊:50462\n死亡人数:3869\n治愈人数:46587\r\n新增确诊:0\r\n现存确诊:6\r\n现存无症状:17\r\n最后更新时间:11月15日16时30分","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"真正的机器人","role":"admin","sex":"unknown","title":"","user_id":2412125282},"sub_type":"normal","time":1636966804,"user_id":2412125282}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:07] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:07] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":144,"packet_sent":103,"packet_lost":0,"message_received":28,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966804}},"time":1636966805}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:10] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:12] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:12] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":144,"packet_sent":103,"packet_lost":0,"message_received":28,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966804}},"time":1636966810}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:15] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:15] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:17] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":145,"packet_sent":104,"packet_lost":0,"message_received":28,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966804}},"time":1636966815}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:17] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:17] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"一般没人买","message_id":-1042557249,"message_seq":1333570,"message_type":"group","post_type":"message","raw_message":"一般没人买","self_id":501273515,"sender":{"age":0,"area":"","card":"id：你的帅爹","level":"","nickname":"棺小棺","role":"member","sex":"unknown","title":"","user_id":550223995},"sub_type":"normal","time":1636966815,"user_id":550223995}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:18] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:20] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:20] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: websocket: close sent 
[2021-11-15 17:00:20] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:20] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":913941037,"message":"我也想换游戏","message_id":-1227037143,"message_seq":1333571,"message_type":"group","post_type":"message","raw_message":"我也想换游戏","self_id":501273515,"sender":{"age":0,"area":"","card":"","level":"","nickname":"华纳手下第一打手DC","role":"member","sex":"unknown","title":"","user_id":1659227257},"sub_type":"normal","time":1636966818,"user_id":1659227257}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:22] [WARNING]: 上报Event数据 {"anonymous":null,"font":0,"group_id":754044548,"message":"[CQ:image,file=8c7aad9eeb04403ba2e4fa6eb8c6651f.image,url=https://gchat.qpic.cn/gchatpic_new/1398017538/754044548-3089608810-8C7AAD9EEB04403BA2E4FA6EB8C6651F/0?term=3,subType=1]","message_id":-217352651,"message_seq":87718,"message_type":"group","post_type":"message","raw_message":"[CQ:image,file=8c7aad9eeb04403ba2e4fa6eb8c6651f.image,subType=1]","self_id":501273515,"sender":{"age":0,"area":"","card":"TREEING ","level":"","nickname":"Mi manchi","role":"member","sex":"unknown","title":"","user_id":1398017538},"sub_type":"normal","time":1636966819,"user_id":1398017538}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
[2021-11-15 17:00:22] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:5701 时出现错误: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 将重试. 
[2021-11-15 17:00:22] [WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":501273515,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":148,"packet_sent":104,"packet_lost":0,"message_received":31,"message_sent":2,"disconnect_times":1,"lost_times":0,"last_message_time":1636966819}},"time":1636966820}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": dial tcp 127.0.0.1:5701: connectex: No connection could be made because the target machine actively refused it. 
